services:
  swag-bot:
    build: .
    container_name: Omega-v73
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data # Для БД
    logging:
      driver: "json-file"
      options:
        max-size: "10m"